    INSERT INTO GUESTBOOK_ENTRY (COMMENT, USER) VALUES ('Great Comment', 'john');
    INSERT INTO GUESTBOOK_ENTRY (COMMENT, USER) VALUES ('Me Too!', 'jane');
    INSERT INTO GUESTBOOK_ENTRY (COMMENT, USER) VALUES ('I agree.', 'alice');
    INSERT INTO GUESTBOOK_ENTRY (COMMENT, USER) VALUES ('Of course!', 'john');